### ISSUE TITLE
BuildManager Fails When Selecting Cluster for Steps

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/robot-operator#112]
### What happened?

Every build step has `.selector` field that determines if the step will be executed on current cluster. BuildManager cannot satisfy this functionality. For example, it sometimes creates a step's job in physical instance even if the step's selector indicates only cloud instance.

### What did you expect to happen?

I expect to see that steps are created in desired instances.

### How can we reproduce it (as minimally and precisely as possible)?

It can be reproduced by applying a BuildManager like this:

```yaml
apiVersion: types.kubefed.io/v1beta1
kind: FederatedBuildManager
metadata:
  name: build-cloudy
  namespace: my-fleet
spec:
  template:
    metadata:
      labels:
        robolaunch.io/target-robot: cloudy
      name: build-cloudy
      namespace: my-fleet
    spec:
      steps:
      - name: rosdep-cloudy
        workspace: cloudy-ws
        command:  "sleep 3"
        selector:
          robolaunch.io/cloud-instance: robot-cloud-02
  placement:
    clusters:
    - name: robot-cloudy-01
    - name: robot-cloud-02
```

### Kubernetes version

All Kubernetes versions
