### ISSUE TITLE
Generate CHANGELOG

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/robot-operator#121]
### What would you like to be updated?

A command for Makefile should be added for generating changelog. `git-chglog` will be used for this. `make changelog` should do the trick. Some commit messages should be ignored such as `refactor` and `build`.

Current config:

```yaml
style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/robolaunch/robot-operator
options:
  commits:
    # filters:
    #   Type:
    #     - feat
    #     - fix
    #     - perf
    #     - refactor
  commit_groups:
    # title_maps:
    #   feat: Features
    #   fix: Bug Fixes
    #   perf: Performance Improvements
    #   refactor: Code Refactoring
  header:
    pattern: "^(\\w*)(?:\\(([\\w\\$\\.\\-\\*\\s]*)\\))?\\:\\s(.*)$"
    pattern_maps:
      - Type
      - Scope
      - Subject
  notes:
    keywords:
      - BREAKING CHANGE
```

Generation:

```bash
git-chglog --config docs/.chglog/config.yml -o CHANGELOG.md
```
