### ISSUE TITLE
Add Environment Specification to Robot API

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/robot-operator#165]
### What would you like to be added?

Closely related to #161

Robot API should contain new fields that determines the environment image and configurations.

### Why is this needed?

It's needed specify provisioning environment for operator.

**Comment by tunahanertekin** [comment]
This format can be used.

```yaml
spec:
  environment: 
    domain: simulation
    application:
      name: carla
      version: 0.9.13
    devspace:
      ubuntuDistro: focal
      desktop: xfce
      version: 0.1.1
```
