### ISSUE TITLE
LaunchManagers cause error if selected cluster does not match with current instance

### ISSUE THREAD

**Issue by tunahanertekin** [robolaunch/robot-operator#68]
### What happened?

When creating a launch manager (with a single launch) with it's `spec.launch[].selector` and it's instance name (cluster name) does not match, controller throws error. The reason was it tries to create a launch pod and cannot populate a container. 

```
2023-01-17T09:21:49Z	ERROR	Reconciler error	{"controller": "launchmanager", "controllerGroup": "robot.roboscale.io", "controllerKind": "LaunchManager", "LaunchManager": {"name":"arcelik-robot","namespace":"my-fleet"}, "namespace": "my-fleet", "name": "arcelik-robot", "reconcileID": "36b24847-87ec-4424-ae8a-6b9771395ce8", "error": "Pod \"arcelik-robot-launch\" is invalid: spec.containers: Required value"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.0/pkg/internal/controller/controller.go:329
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.0/pkg/internal/controller/controller.go:274
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.14.0/pkg/internal/controller/controller.go:235
```

### What did you expect to happen?

It shouldn't try to create pod if it has no launch to create on the current cluster.

### How can we reproduce it (as minimally and precisely as possible)?

It can be reproduced by creating a launch manager with single launch such as:

 ```
# in a cloud instance
apiVersion: robot.roboscale.io/v1alpha1
kind: LaunchManager
metadata:
  labels:
    robolaunch.io/target-robot: sample
    robolaunch.io/target-vdi: sample-dev-vdi
  name: testing-launch-manager
spec:
  launch:
    slam:
      selector:
        robolaunch.io/physical-instance: demo
      workspace: ws-1
      repository: repo1
      namespacing: false
      launchFilePath: slam/launch/bot_slam.launch.py
```

### Kubernetes version

All Kubernetes versions.
